language: cpp
sudo: false
os: linux
dist: trusty

env:
  global:
    MAKEFLAGS='-j 4'

matrix:
  include:
    - env: CI_TARGET=lint
      addons: { apt: { sources: [ llvm-toolchain-trusty-6.0, ubuntu-toolchain-r-test ], packages: [ clang-format-6.0 ] } }
      before_install:
        - mkdir bin && ( cd bin && ln -s /usr/bin/clang-format-6.0 clang-format )
        - export PATH=$TRAVIS_BUILD_DIR/bin:$PATH
      script:
        - ./bootstrap.py ci-lint -v
    - env: CI_TARGET=gcc-7
      addons: { apt: { sources: [ ubuntu-toolchain-r-test ], packages: [ g++-7 ] } }
      script:
        - ./bootstrap.py ci-test gcc-7 -v
    - env: CI_TARGET=clang-6.0
      addons: { apt: { sources: [ llvm-toolchain-trusty-6.0, ubuntu-toolchain-r-test ], packages: [ clang-6.0 ] } }
      script:
        - ./bootstrap.py ci-test clang-6.0 -v
    - env: CI_TARGET=gcc-sanitize
      sudo: required
      addons: { apt: { sources: [ ubuntu-toolchain-r-test ], packages: [ g++-7 ] } }
      script:
        - ./bootstrap.py ci-test gcc-7 sanitize -v
    - env: CI_TARGET=clang-sanitize
      sudo: required
      # Installing a newer g++ voids GCC Bug 60734.
      addons: { apt: { sources: [ llvm-toolchain-trusty-6.0, ubuntu-toolchain-r-test ], packages: [ clang-6.0, g++-7 ] } }
      script:
        - ./bootstrap.py ci-test clang-6.0 sanitize -v
